config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # pages can manage the users model
  resources :pages do 
    resources :users
  end
  
  get '/signup', to: 'users#new', as: 'signup'

  resources :bookings
  resources :rooms

  # this route allow the user to create a new booking in the booking controoler
  get "bookings/:room/new", to: "bookings#new_booking", as: "new_room_booking"

  get "/rooms/:id", to: "rooms#shows"

  root 'pages#index'

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :room, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @rooms = Room.all
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @room = Room.find_by(params[:room_id]) # find the room by ID
    @comment = @room.comments.build(comment_params) # associate the comment with the room
    @comment.user_id = current_user.id
  
    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :room_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>
<!--
  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= comment.room_id %>
  </p>
-->
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <!-- creating hidden value for room id and user id associated with commented room -->
  <%= form.hidden_field(:room_id, value: comment.room_id) %>

  <%= form.hidden_field(:user_id, value: comment.user_id) %>

  <div>
    <%= form.submit "Add Comment", class: "btn btn-outline-success" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div id="new_booking" class="pages_index_background">
  <div class="container">
    <h1 id="edit_comment" class="display-4 text-center my-0 text-muted">Editing Comment</h1>

    <%= render "form", comment: @comment %>

    <br>

    <div>
      <%= link_to "Show this comment", @comment, class: "btn btn-outline-primary" %> |
      <%= link_to "Back to comments", comments_path, class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<!-- navbar for login page-->
<nav class="navbar navbar-info bg-info fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#">
      <%= image_tag "logo_r4r-v01.png", class:"rounded float-start" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-info" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">R4R offcanvas</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
              <%= link_to 'Logout', user_session_path(current_user), data: { turbo_method: :delete }, class: "dropdown-item" %><br>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Room
            </a>

            <ul class="dropdown-menu dropdown-menu-light">
              <%= link_to "List rooms", rooms_path, class: "dropdown-item" %>
              <%= link_to "Create room", new_room_path, class: "dropdown-item" %>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Booking
            </a>
            <ul class="dropdown-menu dropdown-menu-light">
              <%= link_to "List bookings", bookings_path, class: "dropdown-item" %>
            </ul>
          </li>
        </ul>
        <form class="d-flex mt-3" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
</nav> <!-- /navbar for login page-->

<div id="new_booking" class="pages_index_background">
  <div class="container">
    <h1 id="comments" class="display-4 text-center my-0 mt-5 text-muted">Comments</h1>

    <div id="comments">
      <% @comments.each do |comment| %>
        <%= render comment %>

        <%= link_to "Add Comment", new_comment_path, class: "btn btn-outline-success mb-3"  %>

        <p>
          <%= link_to "Show this comment", comment, class: "btn btn-outline-primary mb-5"  %>
          <%= link_to "Back to rooms", rooms_path, class: "btn btn-outline-primary mb-5"  %>
        </p>
      <% end %>
    </div>
  </div>
</div>


<!-- footer-->
<footer class="text-lg-star" style="background-color: #dee2e6; margin-top: 20px">
  <div class="text-center p-3">
    <p id="copyright" class="mb-2">© 2024 Muginga, Laurindo </p>
  </div>
</footer>  <!-- footer-->

app/views/comments/new.html.erb
<div id="new_booking" class="pages_index_background">
  <div class="container">
    <h1 id="new_comment" class="display-4 text-center my-0 text-muted">New Comment</h1>

    <%= render "form", comment: @comment %>

    <br>
    <div style="display: flex">
      <div>
        <%= link_to "Back to comments", comments_path, class: "btn btn-outline-primary mb-5 mx-2" %>
      </div>
      <div id="new_room">
        <%= link_to "Back to rooms", rooms_path, class: "btn btn-outline-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment), class: "btn btn-outline-primary" %> |
  <%= link_to "Back to comments", comments_path, class: "btn btn-outline-primary" %>

  <%= button_to "Delete this comment", @comment, method: :delete, class: "btn btn-outline-danger mb-5" %>
</div>