config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # pages can manage the users model
  resources :pages do 
    resources :users
  end
  
  get '/signup', to: 'users#new', as: 'signup'

  resources :bookings
  resources :rooms

  # this route allow the user to create a new booking in the booking controoler
  get "bookings/:room/new", to: "bookings#new_booking", as: "new_room_booking"

  get "/rooms/:id", to: "rooms#shows"

  root 'pages#index'

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/views/pages/index.html.erb
<div id="pages_index">
  <div class="container mt-5">

    <% if current_user %>
      <h1 style="margin-top: 100px; margin-bottom: 50px">Welcome, <%= current_user.email %>!</h1>
        
        <!-- navbar for login page-->

        <nav class="navbar navbar-info bg-info fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand text-white" href="#"><strong>R4R</strong></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end text-bg-info" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">R4R offcanvas</h5>
              <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Room
                  </a>
                  <ul class="dropdown-menu dropdown-menu-light">
                    <%= link_to "List rooms", rooms_path, class: "dropdown-item" %>
                    <%= link_to "Create room", new_room_path, class: "dropdown-item" %>
                    <li>
                      <hr class="dropdown-divider">
                    </li>

                    <li><a class="dropdown-item" href="#">Editing Room</a></li>
                  </ul>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Booking
                  </a>
                  <ul class="dropdown-menu dropdown-menu-light">
                    <%= link_to "List bookings", bookings_path, class: "dropdown-item" %>

                    <%= link_to "Book room", new_booking_path, class: "dropdown-item" %>
                    <li>
                    <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Editing booking</a></li>
                    
                  </ul>
                </li>
              </ul>
              <form class="d-flex mt-3" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </div>
      </nav> <!-- /navbar for login page-->

      <div class="justify-content-center">
        <%= link_to "List rooms", rooms_path, class: "btn btn-outline-primary mx-5" %>
        <%= link_to 'Log out', user_session_path(current_user), data: { turbo_method: :delete }, class: "btn btn-outline-danger" %><br>
      </div>

    <% else %>

    <!-- welcome page -->
    <section class="bsb-hero-5 px-3 bsb-overlay banner-background-image">
      <div class="container-fluid">
        <div class="row justify-content-md-center align-items-center">
          <div class="col-12 col-md-11 col-lg-9 col-xl-8 col-xxl-7">
            <h2 class="display-1 text-white text-center fw-bold mt-5" style="color: #3949AB">
              Welcome to R4R!
            </h2>
            <p class="lead text-center mb-5 d-flex justify-content-sm-center">
              <span class="col-12 col-sm-10 col-md-8 col-xxl-7">Find your perfect room, make it your own!</span>
            </p>
            
            <div style="display: flex; gap: 10px;" class="justify-content-sm-center">
              <div class="d-grid gap-2 d-sm-flex">
                <%= link_to 'Login', new_user_session_path, class: "btn btn-primary mt-5 mb-5" %>
              </div>

              <div>
                <%= link_to "Sign up", signup_path, class: "btn btn-success mt-5 mb-5" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section> <!-- /welcome page -->

    <% end %>
  </div>
</div>

<!-- footer-->
<footer class="bg-light text-lg-star fixed-bottom" style="background-color: gray; margin-top: 50px">
  <div class="text-center p-3">
    <p id="copyright" class="mb-2">© 2024 Muginga, Laurindo (Eli James) </p>
    <p>Find me on GitHub: <a href="https://github.com/muginga72"><i class="fab fa-github"></i></a></p>
    <p>Contact us: <a href="mailto:lmj.muginga@gmail.com"><i class="fas fa-envelope"></i></a></p>
  </div>
</footer>  <!-- footer-->