config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # pages can manage the users model
  resources :pages do 
    resources :users
  end
  
  get '/signup', to: 'users#new', as: 'signup'

  resources :bookings
  resources :rooms

  # this route allow the user to create a new booking in the booking controoler
  get "bookings/:room/new", to: "bookings#new_booking", as: "new_room_booking"

  get "/rooms/:id", to: "rooms#shows"

  root 'pages#index'

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/room.rb
class Room < ApplicationRecord
  attr_accessor :coming_soon # Define the coming_soon attribute

  belongs_to :user
  has_many :bookings
  has_many :comments

  validates :room_address, presence: true

  # Add the 'booked' attribute
  attribute :booked, :boolean, default: false

  def owner
    user # Return the associated user (owner)
  end
  
  private

  def room_availability
    # check if the room is available for the given time range
    overlapping_bookings = Booking.where(room_id: room_id).where.not(id: id).where(
    '(? <= check_out) AND (check_in <= ?)', check_in, check_out
    )

    # If there are any overlapping reservations, add an error
    if overlapping_bookings.any?
      errors.add(:base, "The room is not available for the selected dates.")
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy destroy_with_comments ]

  # GET /rooms or /rooms.json
  def index
    @room = Room.find_by(params[:id]) # Or however you retrieve the room
    # Get all bookings for the current user 
    @bookings = Booking.where(user_id: current_user.id) # set booking to display it under booked  
    if !params["check_in"] || !params["check_out"]
      @rooms = Room.all 
    else
      # will transform the string to date using parse
      check_in_date = (params["check_in"])
      check_out_date = (params["check_out"])
      
      # joins the rooms to the bookings.
      # we want the rooms they are not having check_in less than check_out_date
      # and check_out greather than the check_in_date
      @rooms = Room.where("NOT EXISTS (:bookings)", bookings: Booking.select("1").where(
        "bookings.room_id = rooms.id AND bookings.check_in < ? AND bookings.check_out > ?", check_out_date, check_in_date))
    end
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    unless @room.user == current_user
      flash[:alert] = "You cannot edit someone else's room."
      redirect_to rooms_path
    end
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    
    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy_with_comments
    if (@room.comments.exists?)
      @room.comments.destroy_all
    end 
    @room.destroy
    redirect_to rooms_path 
  end

  def destroy
    if @room.user == current_user
      @room.destroy!

      respond_to do |format|
        format.html { redirect_to rooms_url, notice: "Room was successfully deleted." }
        format.json { head :no_content }
      end
    else
      redirect_to rooms_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      # @room = Room.find(params[:id])
      @room = Room.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(
        :user_id,
        :room_size, 
        :room_class, 
        :room_status, 
        :room_address, 
        :room_city, 
        :room_state, 
        :room_zip, 
        :room_country, 
        :room_price, 
        :room_description, 
        :room_smoke, 
        :number_of_beds, 
        :bed_size
      )
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container-fluid" style = "margin-botton: 20px">
    <div class="mb-2">
      <%= form.label :room_size, style: "display: block" %>
      <%= form.text_field :room_size, placeholder: "220 sqft" %>
    </div>

    <div class="mb-2">
      <%= form.label :room_class, style: "display: block" %>
      <%= form.select :room_class, ["Single", "Double", "Triple", "Qadruple", "Standard", "Superior", "Delux", "Suite", "Presidential Suite" ] %>
    </div>

    <div class="mb-2">
      <%= form.label :room_status, style: "display: block" %>
      <%= form.select :room_status, ["Available", "Coming soon"] %>
    </div>

    <div class="mb-2">
      <%= form.label :room_address, style: "display: block" %>
      <%= form.text_field :room_address, placeholder: "123 Main St" %>
    </div>

    <div class="mb-2">
      <%= form.label :room_city, style: "display: block" %>
      <%= form.text_field :room_city %>
    </div>

    <div class="mb-2">
      <%= form.label :room_state, style: "display: block" %>
      <%= form.select :room_state, [ "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", 
        "ID", "IL", "IL", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE",
        "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", 
        "UT", "VT", "VA", "WA", "WV", "WI", "WY" ] %>
    </div>

    <div class="mb-2">
      <%= form.label :room_zip, style: "display: block" %>
      <%= form.text_field :room_zip %>
    </div>

    <div class="mb-2">
      <%= form.label :room_country, style: "display: block" %>
      <%= form.text_field :room_country %>
    </div>

    <div class="mb-2">
      <%= form.label :room_price, style: "display: block" %>
      <%= form.text_field :room_price %>
    </div>

    <div class="mb-2">
      <%= form.label :room_smoke, style: "display: block" %>
      <%= form.check_box :room_smoke, class: "form-check-input" %>
    </div>

    <div class="mb-2">
      <%= form.label :number_of_beds, style: "display: block" %>
      <%= form.select :number_of_beds, ["1", "2", "3", "4", "5", "6", "8", "9"]%>
    </div>

    <div class="mb-2">
      <%= form.label :bed_size, style: "display: block" %>
      <%= form.select :bed_size, ["Twin or Single", "Twin XL", "Full or Double", "Full XL", "Queen", "Olympic Queen", "King", "California King"] %>
    </div>

    <div>
      <%= form.label :room_description, style: "display: block" %>
      <%= form.text_area :room_description %>
    </div>

    <div>
      <%= form.submit class: "btn btn-outline-success m-4" %>
    </div>
  <% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Room size:</strong>
    <%= room.room_size %>
  </p>

  <p>
    <strong>Room class:</strong>
    <%= room.room_class %>
  </p>

  <p>
    <strong>Room status:</strong>
    <%= room.room_status %>
  </p>

  <p>
    <strong>Room address:</strong>
    <%= room.room_address %>
  </p>

  <p>
    <strong>Room city:</strong>
    <%= room.room_city %>
  </p>

  <p>
    <strong>Room state:</strong>
    <%= room.room_state %>
  </p>

  <p>
    <strong>Room zip:</strong>
    <%= room.room_zip %>
  </p>

  <p>
    <strong>Room country:</strong>
    <%= room.room_country %>
  </p>

  <p>
    <strong>Room price:</strong>
    <%= room.room_price %>
  </p>

  <p>
    <strong>Room description:</strong>
    <%= room.room_description %>
  </p>

  <p>
    <strong>Room smoke:</strong>
    <%= room.room_smoke %>
  </p>

  <p>
    <strong>Number of beds:</strong>
    <%= room.number_of_beds %>
  </p>

  <p>
    <strong>Bed size:</strong>
    <%= room.bed_size %>
  </p>

</div>

app/views/rooms/edit.html.erb
<div id="new_room" class="pages_index_background">
  <div class="container"> 
    <h1 id="editing_room" class="display-3 text-center my-5 text-muted">Editing room</h1>

    <%= render "form", room: @room %>

    <br>

    <div>
      <%= link_to "Show", @room, class: "btn btn-outline-info" %> |
      <%= link_to "Back", rooms_path, class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<!-- navbar for login page-->
<nav class="navbar navbar-info bg-info fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#">
      <%= image_tag "logo_r4r-v01.png", class:"rounded float-start" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-info" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">R4R offcanvas</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
              <%= link_to 'Logout', user_session_path(current_user), data: { turbo_method: :delete }, class: "dropdown-item" %><br>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Room
            </a>

            <ul class="dropdown-menu dropdown-menu-light">
              <%= link_to "List rooms", rooms_path, class: "dropdown-item" %>
              <%= link_to "Create room", new_room_path, class: "dropdown-item" %>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Booking
            </a>
            <ul class="dropdown-menu dropdown-menu-light">
              <%= link_to "List bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path(current_user), class: "dropdown-item" %>
            </ul>
          </li>
        </ul>
        <form class="d-flex mt-3" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
</nav> <!-- /navbar for login page-->

<!-- banner component --> 
<section class="bsb-hero-5 px-3 bsb-overlay banner-background-image">
  <div class="container-fluid">
    <div class="row justify-content-md-center align-items-center">
      <div class="col-12 col-md-11 col-lg-9 col-xl-8 col-xxl-7">
        <h2 class="display-1 text-white text-center fw-bold mt-5" style="color: #3949AB">
          Welcome to R4R!
        </h2>
        <p class="lead text-white text-center mb-5 d-flex justify-content-sm-center">
          <span class="col-12 col-sm-10 col-md-8 col-xxl-7">Find your perfect room, make it your own!</span>
        </p>
      </div>
    </div>
  </div>
  </div>
</section>

<!-- filter the room based on the availability -->
<div class="container-fluid m-0" style="background-color: #dee2e6">
  <div>
    <div class="text-center my-0 text-muted">
      <%= form_tag(rooms_path, method: :get) do %>
        <%= label_tag(:check_in, "Check in:") %>
        <%= date_field_tag(:check_in) %>
        <%= label_tag(:check_out, "Check out:") %>
        <%= date_field_tag(:check_out) %>
        <%= submit_tag("Search for Room", class: "btn btn-outline-primary m-3") %>
      <% end %>
    </div>
  </div>
</div> <!-- /filter the room based on the availability -->

<div class="container-fluid">
  <div class="row">
    <div class="col-8">
      <h1 id="available" class="display-4 text-center my-3 text-muted">Available Rooms</h1>
      <div class="">
        <div class="row">
          <% if @rooms %>
            <% @rooms.each do |room| %>
              <div class="col-sm-6 col-md-6 d-flex align-items-stretch" style="margin-left: 0px; margin-bottom: 30px">
                <div class="card">
                  <%= image_tag "Bedroom-2.jpg", class: "rounded-top"%>
                  <div class="card-body">
                    <ul class="list-inline">
                      <li>
                        <strong>Size</strong>: <%= room.room_size %>     |
                        <strong>Class</strong>: <%= room.room_class %>    |
                        <strong>Pice</strong>: $<%= room.room_price %>    |
                        <!--<strong>Status</strong>: <%= room.room_status %>     |-->
                        <strong>Number of Beds</strong>: <%= room.number_of_beds %>     |
                        <strong>Bed Size</strong>: <%= room.bed_size %>     |
                        <strong>Smoke</strong>: <%= room.room_smoke %>
                      </li>
                    </ul>
                    <address>
                      <h6>Address</h6>
                      <%= room.room_address %>, <%= room.room_city %>,<br> 
                      <%= room.room_state %>, <%= room.room_zip %>, <%= room.room_country %><br>
                    </address>
                    <div style="display: flex; space-between">
                      <h6 class="card-title">Description </h6>

                      <% if room.room_status == "Available" %>
                        <div style="background-color: #75b798; color: white; border-radius: 8px; margin-left: 20px">
                          <span class="badge badge-secondary">Available</span>
                        </div>
                      <% else %>
                        <div style="background-color: #e09a61; color: white; border-radius: 8px; margin-left: 20px">
                          <span class="badge badge-secondary">Coming soon</span>
                        </div>
                      <% end %>
                    </div>
                    <blockquote>
                      <p><%= room.room_description %></p>
                    </blockquote>

                    <!-- add comment to specific room_id -->
                    <%= link_to "Add Comment", new_comment_path, class: "no-underline" %>
                    
                  </div>
                  <div class="card-footer">
                    <p>
                      <%= link_to "Show room", room, class: "btn btn-outline-primary" %> 
                        
                      <!-- this link to allows user to create a booking from the cards -->
                      <%= link_to "Book room", new_room_booking_path(room), class: "btn btn-outline-success" %>
                    </p>
                  </div>
                </div>
              </div>
            <% end %>
            <% else %>
              <p class="btn btn-primary" style="margin: 40px"> No rooms available</p>
          <% end %>
        </div>
      </div>
    </div>

    <!-- booked rooms session -->
    <div class="col-4">
      <h1 id="available" class="display-4 text-center my-3 text-muted">Booked Rooms</h1>
      <% if @bookings %>
        <% @bookings.each do |booking| %>
        <div class="card">
          <%= image_tag "Bedroom-5.jpg", class: "rounded-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= booking.room.room_description %></h5>
            <address>
              <%= booking.room.room_address %>, <%= booking.room.room_city %>, 
              <%= booking.room.room_state %><br>
            </address>
            <%= link_to "Check this one!", bookings_path(current_user), class: "btn btn-outline-primary" %>
          </div>
        </div>
        <% end %>
      <% else %>
        <div class="card">
        <%= image_tag "Bedroom-5.jpg", class: "rounded-top" %>
          <div class="card-body">
            <h5 class="card-title">Beautiful studio</h5>
            <p class="card-text">The room will be ready for occupancy soon, so keep an eye out for this fantastic opportunity!</p>
            <%= link_to "Check this one!", bookings_path, class: "btn btn-outline-primary" %>
          </div>
        </div>
      <% end %>
    </div><!-- /booked rooms session -->
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            <div class="row">
              <%= image_tag "Bedroom-1.jpg", class: "responsive" %>
            </div>
          </div>
          <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">Coming soon!</h5>
                <p class="card-text">Whether you’re a working professional or a student, this room offers a peaceful retreat after a busy day. The room will be ready for occupancy soon!</p>
                <%= link_to "Learn more!", rooms_path(current_user), class: "btn btn-outline-primary" %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- footer-->
<footer class="bg-light text-lg-star fixed-bottom" style="background-color: gray; margin-top: 50px">
  <div class="text-center p-3">
    <p id="copyright" class="mb-2">© 2024 Muginga, Laurindo (Eli James) </p>
    <p>Find me on GitHub: <a href="https://github.com/muginga72"><i class="fab fa-github"></i></a></p>
    <p>Contact us: <a href="mailto:lmj.muginga@gmail.com"><i class="fas fa-envelope"></i></a></p>
  </div>
</footer>  <!-- footer-->

app/views/rooms/new.html.erb
<div id="new_room" class="pages_index_background">
  <div class="container">
    <h1 id="new_room_title" class="display-4 text-center text-muted">New Room</h1>

    <%= render "form", room: @room %>

    <br>

    <div id="new_room">
      <%= link_to "Back to rooms", rooms_path, class: "btn btn-outline-primary m-3" %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="user_session" class="pages_index_background">
  <div class="container">
  <h1 id="list_users" class="display-4 text-center text-muted">Room Detalis</h1>

  <%= render @room, partial: 'shared/deleteModal' %>

  <div style="margin-bottom: 20px;">
    <%= link_to "Edit room", edit_room_path(@room), class: "btn btn-outline-success", style: "margin-bottom: 20px;" %> 
    <%= link_to "Back to rooms", rooms_path, class: "btn btn-outline-primary", style: "margin-bottom: 20px;"  %>

    <%= button_to "Delete room", @room, method: :delete, class: "btn btn-outline-danger", style: "margin-bottom: 20px;", data: { toggle: "modal", target: "#deleteModal" } %>
  </div>
</div>